// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/ebs/publisher/features/publisher/proto_files/message.proto

package com.ebs.publisher.features.publisher.proto_classes;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:publisher.MsgProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageType = 1;</code>
     * @return The messageType.
     */
    java.lang.String getMessageType();
    /**
     * <code>string messageType = 1;</code>
     * @return The bytes for messageType.
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     * @return Whether the subscription field is set.
     */
    boolean hasSubscription();
    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     * @return The subscription.
     */
    com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getSubscription();
    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     */
    com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder getSubscriptionOrBuilder();

    /**
     * <code>.publisher.PubProto publication = 3;</code>
     * @return Whether the publication field is set.
     */
    boolean hasPublication();
    /**
     * <code>.publisher.PubProto publication = 3;</code>
     * @return The publication.
     */
    com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getPublication();
    /**
     * <code>.publisher.PubProto publication = 3;</code>
     */
    com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder getPublicationOrBuilder();

    public com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code publisher.MsgProto}
   */
  public static final class MsgProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:publisher.MsgProto)
      MsgProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgProto.newBuilder() to construct.
    private MsgProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgProto() {
      messageType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebs.publisher.features.publisher.proto_classes.MessageProto.internal_static_publisher_MsgProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebs.publisher.features.publisher.proto_classes.MessageProto.internal_static_publisher_MsgProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.class, com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.Builder.class);
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SUBSCRIPTION(2),
      PUBLICATION(3),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 2: return SUBSCRIPTION;
          case 3: return PUBLICATION;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageType_ = "";
    /**
     * <code>string messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <code>string messageType = 1;</code>
     * @return The bytes for messageType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBSCRIPTION_FIELD_NUMBER = 2;
    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     * @return Whether the subscription field is set.
     */
    @java.lang.Override
    public boolean hasSubscription() {
      return messageCase_ == 2;
    }
    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     * @return The subscription.
     */
    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getSubscription() {
      if (messageCase_ == 2) {
         return (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_;
      }
      return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
    }
    /**
     * <code>.publisher.SubProto subscription = 2;</code>
     */
    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder getSubscriptionOrBuilder() {
      if (messageCase_ == 2) {
         return (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_;
      }
      return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
    }

    public static final int PUBLICATION_FIELD_NUMBER = 3;
    /**
     * <code>.publisher.PubProto publication = 3;</code>
     * @return Whether the publication field is set.
     */
    @java.lang.Override
    public boolean hasPublication() {
      return messageCase_ == 3;
    }
    /**
     * <code>.publisher.PubProto publication = 3;</code>
     * @return The publication.
     */
    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getPublication() {
      if (messageCase_ == 3) {
         return (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_;
      }
      return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
    }
    /**
     * <code>.publisher.PubProto publication = 3;</code>
     */
    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder getPublicationOrBuilder() {
      if (messageCase_ == 3) {
         return (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_;
      }
      return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
      }
      if (messageCase_ == 2) {
        output.writeMessage(2, (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_);
      }
      if (messageCase_ == 3) {
        output.writeMessage(3, (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
      }
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_);
      }
      if (messageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto)) {
        return super.equals(obj);
      }
      com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto other = (com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto) obj;

      if (!getMessageType()
          .equals(other.getMessageType())) return false;
      if (!getMessageCase().equals(other.getMessageCase())) return false;
      switch (messageCase_) {
        case 2:
          if (!getSubscription()
              .equals(other.getSubscription())) return false;
          break;
        case 3:
          if (!getPublication()
              .equals(other.getPublication())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      switch (messageCase_) {
        case 2:
          hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
          hash = (53 * hash) + getSubscription().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PUBLICATION_FIELD_NUMBER;
          hash = (53 * hash) + getPublication().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code publisher.MsgProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:publisher.MsgProto)
        com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebs.publisher.features.publisher.proto_classes.MessageProto.internal_static_publisher_MsgProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebs.publisher.features.publisher.proto_classes.MessageProto.internal_static_publisher_MsgProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.class, com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.Builder.class);
      }

      // Construct using com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messageType_ = "";
        if (subscriptionBuilder_ != null) {
          subscriptionBuilder_.clear();
        }
        if (publicationBuilder_ != null) {
          publicationBuilder_.clear();
        }
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebs.publisher.features.publisher.proto_classes.MessageProto.internal_static_publisher_MsgProto_descriptor;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto getDefaultInstanceForType() {
        return com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto build() {
        com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto buildPartial() {
        com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto result = new com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.messageType_ = messageType_;
        }
      }

      private void buildPartialOneofs(com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto result) {
        result.messageCase_ = messageCase_;
        result.message_ = this.message_;
        if (messageCase_ == 2 &&
            subscriptionBuilder_ != null) {
          result.message_ = subscriptionBuilder_.build();
        }
        if (messageCase_ == 3 &&
            publicationBuilder_ != null) {
          result.message_ = publicationBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto) {
          return mergeFrom((com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto other) {
        if (other == com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto.getDefaultInstance()) return this;
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        switch (other.getMessageCase()) {
          case SUBSCRIPTION: {
            mergeSubscription(other.getSubscription());
            break;
          }
          case PUBLICATION: {
            mergePublication(other.getPublication());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                messageType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSubscriptionFieldBuilder().getBuilder(),
                    extensionRegistry);
                messageCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getPublicationFieldBuilder().getBuilder(),
                    extensionRegistry);
                messageCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object messageType_ = "";
      /**
       * <code>string messageType = 1;</code>
       * @return The messageType.
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageType = 1;</code>
       * @return The bytes for messageType.
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        messageType_ = getDefaultInstance().getMessageType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 1;</code>
       * @param value The bytes for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder> subscriptionBuilder_;
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       * @return Whether the subscription field is set.
       */
      @java.lang.Override
      public boolean hasSubscription() {
        return messageCase_ == 2;
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       * @return The subscription.
       */
      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getSubscription() {
        if (subscriptionBuilder_ == null) {
          if (messageCase_ == 2) {
            return (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_;
          }
          return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return subscriptionBuilder_.getMessage();
          }
          return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
        }
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      public Builder setSubscription(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto value) {
        if (subscriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          subscriptionBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      public Builder setSubscription(
          com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder builderForValue) {
        if (subscriptionBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          subscriptionBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      public Builder mergeSubscription(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto value) {
        if (subscriptionBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance()) {
            message_ = com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.newBuilder((com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            subscriptionBuilder_.mergeFrom(value);
          } else {
            subscriptionBuilder_.setMessage(value);
          }
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      public Builder clearSubscription() {
        if (subscriptionBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          subscriptionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder getSubscriptionBuilder() {
        return getSubscriptionFieldBuilder().getBuilder();
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder getSubscriptionOrBuilder() {
        if ((messageCase_ == 2) && (subscriptionBuilder_ != null)) {
          return subscriptionBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_;
          }
          return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
        }
      }
      /**
       * <code>.publisher.SubProto subscription = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder> 
          getSubscriptionFieldBuilder() {
        if (subscriptionBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
          }
          subscriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder>(
                  (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        onChanged();
        return subscriptionBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder> publicationBuilder_;
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       * @return Whether the publication field is set.
       */
      @java.lang.Override
      public boolean hasPublication() {
        return messageCase_ == 3;
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       * @return The publication.
       */
      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getPublication() {
        if (publicationBuilder_ == null) {
          if (messageCase_ == 3) {
            return (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_;
          }
          return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
        } else {
          if (messageCase_ == 3) {
            return publicationBuilder_.getMessage();
          }
          return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
        }
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      public Builder setPublication(com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto value) {
        if (publicationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          publicationBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      public Builder setPublication(
          com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder builderForValue) {
        if (publicationBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          publicationBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      public Builder mergePublication(com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto value) {
        if (publicationBuilder_ == null) {
          if (messageCase_ == 3 &&
              message_ != com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance()) {
            message_ = com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.newBuilder((com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 3) {
            publicationBuilder_.mergeFrom(value);
          } else {
            publicationBuilder_.setMessage(value);
          }
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      public Builder clearPublication() {
        if (publicationBuilder_ == null) {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
          }
          publicationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder getPublicationBuilder() {
        return getPublicationFieldBuilder().getBuilder();
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder getPublicationOrBuilder() {
        if ((messageCase_ == 3) && (publicationBuilder_ != null)) {
          return publicationBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 3) {
            return (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_;
          }
          return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
        }
      }
      /**
       * <code>.publisher.PubProto publication = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder> 
          getPublicationFieldBuilder() {
        if (publicationBuilder_ == null) {
          if (!(messageCase_ == 3)) {
            message_ = com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
          }
          publicationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder>(
                  (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 3;
        onChanged();
        return publicationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:publisher.MsgProto)
    }

    // @@protoc_insertion_point(class_scope:publisher.MsgProto)
    private static final com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto();
    }

    public static com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgProto>
        PARSER = new com.google.protobuf.AbstractParser<MsgProto>() {
      @java.lang.Override
      public MsgProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.MessageProto.MsgProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publisher_MsgProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publisher_MsgProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLsrc/main/java/com/ebs/publisher/featur" +
      "es/publisher/proto_files/message.proto\022\t" +
      "publisher\032Hsrc/main/java/com/ebs/publish" +
      "er/features/publisher/proto_files/pub.pr" +
      "oto\032Hsrc/main/java/com/ebs/publisher/fea" +
      "tures/publisher/proto_files/sub.proto\"\203\001" +
      "\n\010MsgProto\022\023\n\013messageType\030\001 \001(\t\022+\n\014subsc" +
      "ription\030\002 \001(\0132\023.publisher.SubProtoH\000\022*\n\013" +
      "publication\030\003 \001(\0132\023.publisher.PubProtoH\000" +
      "B\t\n\007messageBB\n2com.ebs.publisher.feature" +
      "s.publisher.proto_classesB\014MessageProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ebs.publisher.features.publisher.proto_classes.PublicationProto.getDescriptor(),
          com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.getDescriptor(),
        });
    internal_static_publisher_MsgProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_publisher_MsgProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publisher_MsgProto_descriptor,
        new java.lang.String[] { "MessageType", "Subscription", "Publication", "Message", });
    com.ebs.publisher.features.publisher.proto_classes.PublicationProto.getDescriptor();
    com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
