// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/ebs/publisher/features/publisher/proto_files/pub.proto

package com.ebs.publisher.features.publisher.proto_classes;

public final class PublicationProto {
  private PublicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PubProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:publisher.PubProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 stationId = 1;</code>
     * @return The stationId.
     */
    long getStationId();

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>int64 temperature = 3;</code>
     * @return The temperature.
     */
    long getTemperature();

    /**
     * <code>double rainProbability = 4;</code>
     * @return The rainProbability.
     */
    double getRainProbability();

    /**
     * <code>int64 windSpeed = 5;</code>
     * @return The windSpeed.
     */
    long getWindSpeed();

    /**
     * <code>string direction = 6;</code>
     * @return The direction.
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 6;</code>
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code publisher.PubProto}
   */
  public static final class PubProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:publisher.PubProto)
      PubProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PubProto.newBuilder() to construct.
    private PubProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PubProto() {
      city_ = "";
      direction_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PubProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.internal_static_publisher_PubProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.internal_static_publisher_PubProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.class, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder.class);
    }

    public static final int STATIONID_FIELD_NUMBER = 1;
    private long stationId_ = 0L;
    /**
     * <code>int64 stationId = 1;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public long getStationId() {
      return stationId_;
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 3;
    private long temperature_ = 0L;
    /**
     * <code>int64 temperature = 3;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public long getTemperature() {
      return temperature_;
    }

    public static final int RAINPROBABILITY_FIELD_NUMBER = 4;
    private double rainProbability_ = 0D;
    /**
     * <code>double rainProbability = 4;</code>
     * @return The rainProbability.
     */
    @java.lang.Override
    public double getRainProbability() {
      return rainProbability_;
    }

    public static final int WINDSPEED_FIELD_NUMBER = 5;
    private long windSpeed_ = 0L;
    /**
     * <code>int64 windSpeed = 5;</code>
     * @return The windSpeed.
     */
    @java.lang.Override
    public long getWindSpeed() {
      return windSpeed_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object direction_ = "";
    /**
     * <code>string direction = 6;</code>
     * @return The direction.
     */
    @java.lang.Override
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 6;</code>
     * @return The bytes for direction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stationId_ != 0L) {
        output.writeInt64(1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (temperature_ != 0L) {
        output.writeInt64(3, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rainProbability_) != 0) {
        output.writeDouble(4, rainProbability_);
      }
      if (windSpeed_ != 0L) {
        output.writeInt64(5, windSpeed_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, date_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (temperature_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rainProbability_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, rainProbability_);
      }
      if (windSpeed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, windSpeed_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto)) {
        return super.equals(obj);
      }
      com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto other = (com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) obj;

      if (getStationId()
          != other.getStationId()) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (getTemperature()
          != other.getTemperature()) return false;
      if (java.lang.Double.doubleToLongBits(getRainProbability())
          != java.lang.Double.doubleToLongBits(
              other.getRainProbability())) return false;
      if (getWindSpeed()
          != other.getWindSpeed()) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStationId());
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTemperature());
      hash = (37 * hash) + RAINPROBABILITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRainProbability()));
      hash = (37 * hash) + WINDSPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWindSpeed());
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code publisher.PubProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:publisher.PubProto)
        com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.internal_static_publisher_PubProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.internal_static_publisher_PubProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.class, com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.Builder.class);
      }

      // Construct using com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationId_ = 0L;
        city_ = "";
        temperature_ = 0L;
        rainProbability_ = 0D;
        windSpeed_ = 0L;
        direction_ = "";
        date_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.internal_static_publisher_PubProto_descriptor;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getDefaultInstanceForType() {
        return com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto build() {
        com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto buildPartial() {
        com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto result = new com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationId_ = stationId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.temperature_ = temperature_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.rainProbability_ = rainProbability_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.windSpeed_ = windSpeed_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.direction_ = direction_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto) {
          return mergeFrom((com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto other) {
        if (other == com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto.getDefaultInstance()) return this;
        if (other.getStationId() != 0L) {
          setStationId(other.getStationId());
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTemperature() != 0L) {
          setTemperature(other.getTemperature());
        }
        if (other.getRainProbability() != 0D) {
          setRainProbability(other.getRainProbability());
        }
        if (other.getWindSpeed() != 0L) {
          setWindSpeed(other.getWindSpeed());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                stationId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                temperature_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 33: {
                rainProbability_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                windSpeed_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                direction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long stationId_ ;
      /**
       * <code>int64 stationId = 1;</code>
       * @return The stationId.
       */
      @java.lang.Override
      public long getStationId() {
        return stationId_;
      }
      /**
       * <code>int64 stationId = 1;</code>
       * @param value The stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationId(long value) {
        
        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 stationId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long temperature_ ;
      /**
       * <code>int64 temperature = 3;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public long getTemperature() {
        return temperature_;
      }
      /**
       * <code>int64 temperature = 3;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(long value) {
        
        temperature_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 temperature = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000004);
        temperature_ = 0L;
        onChanged();
        return this;
      }

      private double rainProbability_ ;
      /**
       * <code>double rainProbability = 4;</code>
       * @return The rainProbability.
       */
      @java.lang.Override
      public double getRainProbability() {
        return rainProbability_;
      }
      /**
       * <code>double rainProbability = 4;</code>
       * @param value The rainProbability to set.
       * @return This builder for chaining.
       */
      public Builder setRainProbability(double value) {
        
        rainProbability_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double rainProbability = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRainProbability() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rainProbability_ = 0D;
        onChanged();
        return this;
      }

      private long windSpeed_ ;
      /**
       * <code>int64 windSpeed = 5;</code>
       * @return The windSpeed.
       */
      @java.lang.Override
      public long getWindSpeed() {
        return windSpeed_;
      }
      /**
       * <code>int64 windSpeed = 5;</code>
       * @param value The windSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setWindSpeed(long value) {
        
        windSpeed_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 windSpeed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        windSpeed_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 6;</code>
       * @return The direction.
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 6;</code>
       * @return The bytes for direction.
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 6;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        direction_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        direction_ = getDefaultInstance().getDirection();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 6;</code>
       * @param value The bytes for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        direction_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 7;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:publisher.PubProto)
    }

    // @@protoc_insertion_point(class_scope:publisher.PubProto)
    private static final com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto();
    }

    public static com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PubProto>
        PARSER = new com.google.protobuf.AbstractParser<PubProto>() {
      @java.lang.Override
      public PubProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PubProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PubProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.PublicationProto.PubProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publisher_PubProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publisher_PubProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHsrc/main/java/com/ebs/publisher/featur" +
      "es/publisher/proto_files/pub.proto\022\tpubl" +
      "isher\"\215\001\n\010PubProto\022\021\n\tstationId\030\001 \001(\003\022\014\n" +
      "\004city\030\002 \001(\t\022\023\n\013temperature\030\003 \001(\003\022\027\n\017rain" +
      "Probability\030\004 \001(\001\022\021\n\twindSpeed\030\005 \001(\003\022\021\n\t" +
      "direction\030\006 \001(\t\022\014\n\004date\030\007 \001(\tBF\n2com.ebs" +
      ".publisher.features.publisher.proto_clas" +
      "sesB\020PublicationProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_publisher_PubProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_publisher_PubProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publisher_PubProto_descriptor,
        new java.lang.String[] { "StationId", "City", "Temperature", "RainProbability", "WindSpeed", "Direction", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
