// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/ebs/publisher/features/publisher/proto_files/sub.proto

package com.ebs.publisher.features.publisher.proto_classes;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:publisher.SubProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    int getInfoCount();
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    boolean containsInfo(
        java.lang.String key);
    /**
     * Use {@link #getInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getInfo();
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getInfoMap();
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    /* nullable */
java.lang.String getInfoOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    java.lang.String getInfoOrThrow(
        java.lang.String key);

    /**
     * <code>repeated string operator = 2;</code>
     * @return A list containing the operator.
     */
    java.util.List<java.lang.String>
        getOperatorList();
    /**
     * <code>repeated string operator = 2;</code>
     * @return The count of operator.
     */
    int getOperatorCount();
    /**
     * <code>repeated string operator = 2;</code>
     * @param index The index of the element to return.
     * @return The operator at the given index.
     */
    java.lang.String getOperator(int index);
    /**
     * <code>repeated string operator = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the operator at the given index.
     */
    com.google.protobuf.ByteString
        getOperatorBytes(int index);
  }
  /**
   * Protobuf type {@code publisher.SubProto}
   */
  public static final class SubProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:publisher.SubProto)
      SubProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubProto.newBuilder() to construct.
    private SubProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubProto() {
      operator_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.class, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder.class);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    private static final class InfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_InfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> info_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInfo() {
      if (info_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InfoDefaultEntryHolder.defaultEntry);
      }
      return info_;
    }
    public int getInfoCount() {
      return internalGetInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    @java.lang.Override
    public boolean containsInfo(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInfoMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInfo() {
      return getInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getInfoMap() {
      return internalGetInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getInfoOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; info = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int OPERATOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList operator_;
    /**
     * <code>repeated string operator = 2;</code>
     * @return A list containing the operator.
     */
    public com.google.protobuf.ProtocolStringList
        getOperatorList() {
      return operator_;
    }
    /**
     * <code>repeated string operator = 2;</code>
     * @return The count of operator.
     */
    public int getOperatorCount() {
      return operator_.size();
    }
    /**
     * <code>repeated string operator = 2;</code>
     * @param index The index of the element to return.
     * @return The operator at the given index.
     */
    public java.lang.String getOperator(int index) {
      return operator_.get(index);
    }
    /**
     * <code>repeated string operator = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the operator at the given index.
     */
    public com.google.protobuf.ByteString
        getOperatorBytes(int index) {
      return operator_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetInfo(),
          InfoDefaultEntryHolder.defaultEntry,
          1);
      for (int i = 0; i < operator_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operator_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        info__ = InfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, info__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < operator_.size(); i++) {
          dataSize += computeStringSizeNoTag(operator_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOperatorList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto)) {
        return super.equals(obj);
      }
      com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto other = (com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) obj;

      if (!internalGetInfo().equals(
          other.internalGetInfo())) return false;
      if (!getOperatorList()
          .equals(other.getOperatorList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetInfo().getMap().isEmpty()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetInfo().hashCode();
      }
      if (getOperatorCount() > 0) {
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + getOperatorList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code publisher.SubProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:publisher.SubProto)
        com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.class, com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.Builder.class);
      }

      // Construct using com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableInfo().clear();
        operator_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.internal_static_publisher_SubProto_descriptor;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getDefaultInstanceForType() {
        return com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto build() {
        com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto buildPartial() {
        com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto result = new com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          operator_ = operator_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.operator_ = operator_;
      }

      private void buildPartial0(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.info_ = internalGetInfo();
          result.info_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto) {
          return mergeFrom((com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto other) {
        if (other == com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto.getDefaultInstance()) return this;
        internalGetMutableInfo().mergeFrom(
            other.internalGetInfo());
        bitField0_ |= 0x00000001;
        if (!other.operator_.isEmpty()) {
          if (operator_.isEmpty()) {
            operator_ = other.operator_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOperatorIsMutable();
            operator_.addAll(other.operator_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                info__ = input.readMessage(
                    InfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableInfo().getMutableMap().put(
                    info__.getKey(), info__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureOperatorIsMutable();
                operator_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> info_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetInfo() {
        if (info_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              InfoDefaultEntryHolder.defaultEntry);
        }
        return info_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableInfo() {
        if (info_ == null) {
          info_ = com.google.protobuf.MapField.newMapField(
              InfoDefaultEntryHolder.defaultEntry);
        }
        if (!info_.isMutable()) {
          info_ = info_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return info_;
      }
      public int getInfoCount() {
        return internalGetInfo().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      @java.lang.Override
      public boolean containsInfo(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getInfoMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getInfo() {
        return getInfoMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getInfoMap() {
        return internalGetInfo().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getInfoOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getInfoOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      public Builder removeInfo(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableInfo() {
        bitField0_ |= 0x00000001;
        return internalGetMutableInfo().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      public Builder putInfo(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableInfo().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; info = 1;</code>
       */
      public Builder putAllInfo(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableInfo().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      private com.google.protobuf.LazyStringList operator_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOperatorIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          operator_ = new com.google.protobuf.LazyStringArrayList(operator_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @return A list containing the operator.
       */
      public com.google.protobuf.ProtocolStringList
          getOperatorList() {
        return operator_.getUnmodifiableView();
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @return The count of operator.
       */
      public int getOperatorCount() {
        return operator_.size();
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param index The index of the element to return.
       * @return The operator at the given index.
       */
      public java.lang.String getOperator(int index) {
        return operator_.get(index);
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the operator at the given index.
       */
      public com.google.protobuf.ByteString
          getOperatorBytes(int index) {
        return operator_.getByteString(index);
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param index The index to set the value at.
       * @param value The operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperator(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureOperatorIsMutable();
        operator_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param value The operator to add.
       * @return This builder for chaining.
       */
      public Builder addOperator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureOperatorIsMutable();
        operator_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param values The operator to add.
       * @return This builder for chaining.
       */
      public Builder addAllOperator(
          java.lang.Iterable<java.lang.String> values) {
        ensureOperatorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, operator_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperator() {
        operator_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operator = 2;</code>
       * @param value The bytes of the operator to add.
       * @return This builder for chaining.
       */
      public Builder addOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureOperatorIsMutable();
        operator_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:publisher.SubProto)
    }

    // @@protoc_insertion_point(class_scope:publisher.SubProto)
    private static final com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto();
    }

    public static com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubProto>
        PARSER = new com.google.protobuf.AbstractParser<SubProto>() {
      @java.lang.Override
      public SubProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ebs.publisher.features.publisher.proto_classes.SubscriptionProto.SubProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publisher_SubProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publisher_SubProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publisher_SubProto_InfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publisher_SubProto_InfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHsrc/main/java/com/ebs/publisher/featur" +
      "es/publisher/proto_files/sub.proto\022\tpubl" +
      "isher\"v\n\010SubProto\022+\n\004info\030\001 \003(\0132\035.publis" +
      "her.SubProto.InfoEntry\022\020\n\010operator\030\002 \003(\t" +
      "\032+\n\tInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001BG\n2com.ebs.publisher.features.publ" +
      "isher.proto_classesB\021SubscriptionProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_publisher_SubProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_publisher_SubProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publisher_SubProto_descriptor,
        new java.lang.String[] { "Info", "Operator", });
    internal_static_publisher_SubProto_InfoEntry_descriptor =
      internal_static_publisher_SubProto_descriptor.getNestedTypes().get(0);
    internal_static_publisher_SubProto_InfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publisher_SubProto_InfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
